-- 1. Profiles Table (Sync with Auth)
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  username text unique,
  role text default 'caylak' check (role in ('caylak', 'yazar', 'yonetici')),
  avatar_url text,
  is_verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (id)
);

-- 2. Categories Table
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  "order" integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Topics Table
create table public.topics (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  category_id bigint references public.categories,
  user_id uuid references public.profiles not null,
  is_locked boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Entries Table
create table public.entries (
  id bigint generated by default as identity primary key,
  content text not null,
  topic_id bigint references public.topics on delete cascade not null,
  user_id uuid references public.profiles not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone
);

-- 5. Reactions Table
create table public.reactions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles not null,
  entry_id bigint references public.entries on delete cascade not null,
  type text check (type in ('applause', 'hiss')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, entry_id)
);

-- 6. Saved Entries Table
create table public.saved_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles not null,
  entry_id bigint references public.entries on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, entry_id)
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.topics enable row level security;
alter table public.entries enable row level security;
alter table public.reactions enable row level security;
alter table public.saved_entries enable row level security;

-- Create Policies (Simplified for initial startup)
-- Allow public read access
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Categories are viewable by everyone." on public.categories for select using (true);
create policy "Topics are viewable by everyone." on public.topics for select using (true);
create policy "Entries are viewable by everyone." on public.entries for select using (true);

-- Allow authenticated insert
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Authenticated users can create topics." on public.topics for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can create entries." on public.entries for insert with check (auth.role() = 'authenticated');

-- Handle On User Created (Trigger to create profile)
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, username, role, avatar_url)
  values (new.id, new.raw_user_meta_data->>'username', 'caylak', '');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Seed Initial Data (Categories)
insert into public.categories (name, slug, "order") values
('Gündem', 'gundem', 1),
('Siyaset', 'siyaset', 2),
('Spor', 'spor', 3),
('Teknoloji', 'teknoloji', 4),
('Eğlence', 'eglence', 5),
('İlişkiler', 'iliskiler', 6);
